[tool.poetry]
name = "rapt-ble"
version = "0.1.1"
description = "Parser for the RAPT Pill hydrometer BLE packets."
authors = ["Jan Čermák <sairon@sairon.cz>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/sairon/rapt-ble"
documentation = "https://rapt-ble.readthedocs.io"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
]
packages = [
    { include = "rapt_ble", from = "src" },
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/sairon/rapt-ble/issues"
"Changelog" = "https://github.com/sairon/rapt-ble/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.9"
bluetooth-sensor-state-data = ">=1.6.1"
home-assistant-bluetooth = ">=1.9.2"
sensor-state-data = ">=2.13.0"
bluetooth-data-tools = ">=0.3.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
pytest-cov = "^3.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
myst-parser = ">=0.16"
sphinx = ">=4.0"
sphinx-rtd-theme = ">=1.0"

[tool.semantic_release]
branch = "main"
version_toml = "pyproject.toml:tool.poetry.version"
version_variable = "src/rapt_ble/__init__.py:__version__"
build_command = "pip install poetry && poetry build"

[tool.pytest.ini_options]
addopts = "-v -Wdefault --cov=rapt_ble --cov-report=term-missing:skip-covered"
pythonpath = ["src"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@overload",
    "if TYPE_CHECKING",
    "raise NotImplementedError",
    'if __name__ == "__main__":',
]

[tool.isort]
profile = "black"
known_first_party = ["rapt_ble", "tests"]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
mypy_path = "src/"
no_implicit_optional = true
show_error_codes = true
warn_unreachable = true
warn_unused_ignores = true
exclude = [
    'docs/.*',
    'setup.py',
]

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true

[[tool.mypy.overrides]]
module = "docs.*"
ignore_errors = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
